name: Build and Deploy React App

on:
  pull_request:
    branches:
      - main
    types:
      - closed # Only run when PR is closed
  workflow_dispatch: # Allows manual triggering

jobs:
  build_and_deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for multi-platform builds if needed
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build Docker image and tag it with the latest tag
      - name: Build Docker image
        run: docker build -t "${{ secrets.DOCKER_USERNAME }}/datalus-ie:latest" .

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push "${{ secrets.DOCKER_USERNAME }}/datalus-ie:latest"

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            docker pull "${{ secrets.DOCKER_USERNAME }}/datalus-ie:latest"
            docker stop datalus-app || true
            docker rm datalus-app || true
            docker run -d --name datalus-app -p 3000:80 \
              "${{ secrets.DOCKER_USERNAME }}/datalus-ie:latest"